=== nicolas-budin/plausex/doc/plausex/do-b-13.05-SHS-07.xsd
<?xml version="1.0" encoding="UTF-8"?><!-- 2023-07-19	Deletion of the 2 blank characters at the end of "shsStringRequiredType " on lines 268 and 269, which can cause errors depending on the program used.==========2023-09-20	Change the type of elements on complexType to improve the check of the structure (RootNode Delivery is required)==========--><!-- SHS Mod --><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://bfs.ch/shs/delivery/validation" targetNamespace="http://bfs.ch/shs/delivery/validation" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.5">	<xs:annotation>		<xs:documentation xml:lang="en">Issue date: 19.07.2023</xs:documentation>	</xs:annotation>	<!-- Declaration of specific types **********************************************************************-->	<xs:simpleType name="shsIsProdType">		<xs:restriction base="xs:string">			<xs:enumeration value="0"/>			<xs:enumeration value="1"/>			<xs:enumeration value="true"/>			<xs:enumeration value="false"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsStringRequiredType">		<xs:restriction base="xs:string">			<xs:minLength value="1"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsDateType">		<xs:union memberTypes="xs:date">			<xs:simpleType>				<xs:restriction base="xs:string">					<xs:length value="0"/>				</xs:restriction>				<!-- Leerstring -->			</xs:simpleType>		</xs:union>	</xs:simpleType>	<xs:simpleType name="shsCodeType">		<xs:union memberTypes="xs:nonNegativeInteger">			<xs:simpleType>				<xs:restriction base="xs:string">					<xs:length value="0"/>				</xs:restriction>			</xs:simpleType>		</xs:union>	</xs:simpleType>	<xs:simpleType name="shsBetragType">		<xs:union>			<xs:simpleType>				<xs:restriction base="xs:decimal">					<xs:totalDigits value="10"/>					<xs:fractionDigits value="2"/>				</xs:restriction>			</xs:simpleType>			<xs:simpleType>				<xs:restriction base="xs:string">					<xs:length value="0" fixed="1"/>				</xs:restriction>			</xs:simpleType>		</xs:union>	</xs:simpleType>	<xs:simpleType name="shsToken20Type">		<xs:restriction base="xs:token">			<xs:maxLength value="20"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsToken30Type">		<xs:restriction base="xs:token">			<xs:maxLength value="30"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsToken50Type">		<xs:restriction base="xs:token">			<xs:maxLength value="50"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsToken150Type">		<xs:restriction base="xs:token">			<xs:maxLength value="150"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="HistoryMunicipalityIdType">		<xs:restriction base="xs:int">			<xs:minInclusive value="10001"/>			<xs:maxInclusive value="99999"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsVnType">		<xs:union>			<xs:simpleType>				<xs:restriction base="xs:unsignedLong">					<xs:minInclusive value="7560000000001"/>					<xs:maxInclusive value="7569999999999"/>				</xs:restriction>			</xs:simpleType>			<xs:simpleType>				<xs:restriction base="xs:string">					<xs:length value="0"/>				</xs:restriction>			</xs:simpleType>		</xs:union>	</xs:simpleType>	<xs:simpleType name="baseNameType">		<xs:restriction base="xs:token">			<xs:maxLength value="100"/>			<xs:minLength value="1"/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsSexType">		<xs:restriction base="xs:string">			<xs:enumeration value="1"/>			<xs:enumeration value="2"/>			<xs:enumeration value="3"/>			<xs:enumeration value=""/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsMaritalStatusType">		<xs:restriction base="xs:string">			<xs:enumeration value="1"/>			<xs:enumeration value="2"/>			<xs:enumeration value="3"/>			<xs:enumeration value="4"/>			<xs:enumeration value="5"/>			<xs:enumeration value="6"/>			<xs:enumeration value="7"/>			<xs:enumeration value="9"/>			<xs:enumeration value=""/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsSeparationType">		<xs:restriction base="xs:string">			<xs:enumeration value="1"/>			<xs:enumeration value="2"/>			<xs:enumeration value=""/>		</xs:restriction>	</xs:simpleType>	<xs:simpleType name="shsCountryIdType">		<xs:union>			<xs:simpleType>				<xs:restriction base="xs:token">					<xs:minLength value="3"/>					<xs:maxLength value="3"/>				</xs:restriction>			</xs:simpleType>			<xs:simpleType>				<xs:restriction base="xs:token">					<xs:length value="0"/>				</xs:restriction>			</xs:simpleType>		</xs:union>	</xs:simpleType>	<xs:complexType name="infosType">		<xs:sequence>			<xs:element name="ffsInfos">				<xs:complexType>					<xs:sequence>						<xs:element name="ffsId" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>						<xs:element name="ffsVersion" type="shsStringRequiredType" minOccurs="1" maxOccurs="1"/>					</xs:sequence>				</xs:complexType>			</xs:element>			<xs:element name="expInfos">				<xs:complexType>					<xs:sequence>						<xs:element name="supplierId" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>						<xs:element name="extractionDateTime" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>						<xs:element name="referenceDate" type="xs:date" minOccurs="1" maxOccurs="1"/>						<xs:element name="isProd" type="shsIsProdType"/>					</xs:sequence>				</xs:complexType>			</xs:element>		</xs:sequence>	</xs:complexType>	<xs:complexType name="dossiersType">		<xs:sequence>			<xs:element type="dossierType" name="dossier" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="dossierType">		<xs:sequence>			<xs:element name="serviceId" type="xs:string" minOccurs="1" maxOccurs="1"/>			<xs:element name="serviceDescription" type="xs:string" minOccurs="1" maxOccurs="1"/>			<xs:element name="socialBenefitCode" type="shsStringRequiredType" minOccurs="1" maxOccurs="1"/>			<xs:element name="socialBenefitDesc" type="shsStringRequiredType" minOccurs="1" maxOccurs="1"/>			<xs:element name="municipalityId" type="HistoryMunicipalityIdType" minOccurs="1" maxOccurs="1"/>			<xs:element name="residentialStatus" type="shsCodeType" minOccurs="1" maxOccurs="1"/>			<xs:element name="rentFullApartment" type="shsBetragType" minOccurs="1" maxOccurs="1"/>			<xs:element name="rentShare" type="shsBetragType" minOccurs="1" maxOccurs="1"/>			<xs:element name="apartmentSize" type="shsCodeType" minOccurs="1" maxOccurs="1"/>			<xs:element name="hhMembers" type="shsCodeType" minOccurs="1" maxOccurs="1"/>			<xs:element name="closingReason" type="shsCodeType" minOccurs="1" maxOccurs="1"/>			<xs:element name="dossierRespPersonId" type="xs:string" minOccurs="1" maxOccurs="1"/>			<xs:element name="dossierRespPersonName" type="xs:string" minOccurs="1" maxOccurs="1"/>			<xs:element name="dateStartEntitlement" type="shsDateType" minOccurs="1" maxOccurs="1"/>			<xs:element type="addressCorrespondenceType" name="addressCorrespondence" minOccurs="1" maxOccurs="1"/>			<xs:element type="personsType" name="persons" minOccurs="1" maxOccurs="1"/>		</xs:sequence>		<xs:attribute name="dossierId" type="shsStringRequiredType" use="required"/>		<xs:attribute name="dossierProfId" type="shsStringRequiredType" use="required"/>	</xs:complexType>		<xs:complexType name="addressCorrespondenceType">		<xs:sequence>			<xs:element name="organisationName" type="shsToken50Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="firstName" type="shsToken30Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="lastName" type="shsToken30Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="street" type="shsToken150Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="houseNumber" type="shsToken30Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="postOfficeBox" type="shsToken20Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="swissZipCode" type="shsToken20Type" minOccurs="1" maxOccurs="1"/>			<xs:element name="town" type="shsToken50Type" minOccurs="1" maxOccurs="1"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="personsType">		<xs:sequence>			<xs:element type="personType" name="person" minOccurs="0" maxOccurs="30"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="personType">		<xs:sequence>			<xs:element name="vn" type="shsVnType" nillable="true"/>			<xs:element name="officialName" type="baseNameType"/>			<xs:element name="firstName" type="baseNameType"/>			<xs:element name="dateOfBirth" type="shsDateType"/>			<xs:element name="sex" type="shsSexType"/>			<xs:element name="maritalStatus" type="shsMaritalStatusType"/>			<xs:element name="separation" type="shsSeparationType"/>			<xs:element name="countryId" type="shsCountryIdType"/>			<xs:element name="education" type="shsCodeType"/>			<xs:element name="educationLevel" type="shsCodeType"/>			<xs:element name="employmentSituation" type="shsCodeType"/>			<xs:element name="employmentRate" type="shsCodeType"/>			<xs:element name="relationshipToApplicant" type="shsCodeType"/>			<xs:element name="foreignerCategoryId" type="xs:string"/>			<xs:element name="foreignerCategoryDesc" type="xs:string"/>			<xs:element name="datEntry" type="shsDateType"/>		</xs:sequence>		<xs:attribute name="personId" type="shsStringRequiredType" use="required"/>		<xs:attribute name="PersonProfId" type="shsStringRequiredType" use="required"/>	</xs:complexType>	<xs:complexType name="accountingEntriesType">		<xs:sequence>			<xs:element type="accountingEntryType" name="accountingEntry" minOccurs="0" maxOccurs="unbounded"/>		</xs:sequence>	</xs:complexType>	<xs:complexType name="accountingEntryType">		<xs:sequence>			<xs:element name="accountingEntryCode" type="shsStringRequiredType"/>			<xs:element name="accountingEntryCodeDesc" type="shsStringRequiredType"/>			<xs:element name="amount" type="shsBetragType"/>			<xs:element name="datRegistration" type="xs:date"/>			<xs:element name="datAccountingEntry" type="shsDateType"/>			<xs:element name="datSubjectFrom" type="shsDateType"/>			<xs:element name="datSubjectTo" type="shsDateType"/>		</xs:sequence>		<xs:attribute name="accountingEntryId" type="shsStringRequiredType" use="required"/>		<xs:attribute name="accountingEntryProfId" type="shsStringRequiredType" use="required"/>		<xs:attribute name="dossierIdRef" type="xs:string" use="required"/>		<xs:attribute name="personIdRef" type="xs:string" use="required"/>	</xs:complexType>	<!-- Structure ******************************************************************************************-->	<xs:element name="delivery">		<xs:complexType>			<xs:sequence>				<xs:element type="infosType" name="infos" minOccurs="1" maxOccurs="1"/>				<xs:element type="dossiersType" name="dossiers" minOccurs="1" maxOccurs="1"/>				<xs:element type="accountingEntriesType" name="accountingEntries" minOccurs="1" maxOccurs="1"/>			</xs:sequence>		</xs:complexType>	</xs:element></xs:schema>

=== nicolas-budin/plausex/doc/plausex/dz-b-13.05-SHS-01.xml
<?xml version="1.0" encoding="utf-8"?>
<delivery
xmlns="http://bfs.ch/shs/delivery/validation"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://bfs.ch/shs/delivery/validation do-b-13.05-SHS-07.xsd">
  <infos>
    <ffsInfos>
      <ffsId>11</ffsId>
      <ffsVersion>6.6.3.5</ffsVersion>
    </ffsInfos>
    <expInfos>
	  <supplierId>15367</supplierId>
	  <extractionDateTime>2022-11-09T16:00:00</extractionDateTime>
	  <referenceDate>2021-01-01</referenceDate>
	  <isProd>1</isProd>     
    </expInfos>
  </infos>
  <dossiers>
	<dossier dossierId="1" dossierProfId="3">
		<serviceId>123</serviceId>
		<serviceDescription>code 123</serviceDescription>
		<socialBenefitCode>code service</socialBenefitCode>
		<socialBenefitDesc>desc service</socialBenefitDesc>
		<municipalityId>33333</municipalityId>
		<residentialStatus></residentialStatus> 
		<rentFullApartment></rentFullApartment>
		<rentShare></rentShare>
		<apartmentSize></apartmentSize>
		<hhMembers></hhMembers>
		<closingReason></closingReason>
		<dossierRespPersonId></dossierRespPersonId>
		<dossierRespPersonName></dossierRespPersonName>
		<dateStartEntitlement></dateStartEntitlement>
		<addressCorrespondence>
			<organisationName>Organisation Test</organisationName>
			<firstName>Jean</firstName>
			<lastName>Dupont</lastName>
			<street>Rue de la Gare</street>
			<houseNumber>20</houseNumber>
			<postOfficeBox>CP 2010</postOfficeBox>
			<swissZipCode>2000</swissZipCode>
			<town>Neuch√¢tel</town>
		</addressCorrespondence>
		<persons>
			<person personId="120" PersonProfId="11">
				<vn></vn>
				<officialName>A</officialName>
				<firstName>A</firstName>
				<dateOfBirth>2001-01-02</dateOfBirth>
				<sex>1</sex>
				<maritalStatus></maritalStatus>
				<separation>1</separation>
				<countryId></countryId>
				<education></education>
				<educationLevel></educationLevel>
				<employmentSituation></employmentSituation>
				<employmentRate></employmentRate>
				<relationshipToApplicant></relationshipToApplicant>
				<foreignerCategoryId></foreignerCategoryId>
				<foreignerCategoryDesc></foreignerCategoryDesc>
				<datEntry></datEntry>				
			</person>
		</persons>	
	</dossier>
  </dossiers>
  <accountingEntries>
	<accountingEntry accountingEntryId="A" accountingEntryProfId="1" dossierIdRef="1" personIdRef="101">	
		<accountingEntryCode>A-25</accountingEntryCode>
		<accountingEntryCodeDesc>AideAuLoyer</accountingEntryCodeDesc>
		<amount>12.25</amount>
		<datRegistration>2022-11-03</datRegistration>
		<datAccountingEntry></datAccountingEntry>
		<datSubjectFrom></datSubjectFrom>
		<datSubjectTo></datSubjectTo>
	</accountingEntry>
	<accountingEntry accountingEntryId="B" accountingEntryProfId="1" dossierIdRef="1" personIdRef="101">	
		<accountingEntryCode>A-25</accountingEntryCode>
		<accountingEntryCodeDesc>AideAuLoyer</accountingEntryCodeDesc>
		<amount>12.25</amount>
		<datRegistration>2022-11-03</datRegistration>
		<datAccountingEntry></datAccountingEntry>
		<datSubjectFrom></datSubjectFrom>
		<datSubjectTo></datSubjectTo>
	</accountingEntry>
  </accountingEntries>
</delivery>
